server:
  port: 4555

management:
  endpoint:
    health:
      show-details: "always"
  endpoints:
    web:
      base-path: /
      exposure:
        include: health, info, prometheus

spring:
  application:
    name: PCQ Consolidation Service

core_case_data:
  api:
    url: ${CORE_CASE_DATA_API_URL:http://localhost:4452}

idam:
  s2s-auth:
    url:    ${S2S_URL:http://localhost:4502}
    secret: ${S2S_SECRET:AAAAAAAAAAAAAAAA}
    name:   ${S2S_NAME:pcq_consolidation_service}
  api:
    url: ${IDAM_API_URL:http://localhost:5000}
  client:
    id: ${IDAM_CLIENT_NAME:ccd_gateway}
    secret: ${IDAM_CLIENT_SECRET:ccd_gateway_secret}
    redirect_uri: ${IDAM_CLIENT_REDIRECT_URI:http://localhost:3451/oauth2redirect}
  users:
    pcq:
      username: ${IDAM_USERS_PCQ_USERNAME:pcq.extractor.ccd@gmail.com}
      password: ${IDAM_USERS_PCQ_PASSWORD:Pa55word11}

service-config:
  services:
    - service: probate
      case-field-mappings:
        - actor: APPLICANT
          name: pcqId
      case-type-ids:
        - Caveat
        - GrantOfRepresentation
    - service: divorce
      case-field-mappings:
        - actor: PETITIONER
          name: PetitionerPcqId
        - actor: RESPONDENT
          name: RespondentPcqId
      case-type-ids:
        - DIVORCE
    - service: cmc
      case-field-mappings:
        - actor: CLAIMANT
          name: applicants.pcqId
        - actor: DEFENDANT
          name: respondents.pcqId
      case-type-ids:
        - MoneyClaimCase
    - service: sscs
      case-field-mappings:
        - actor: APPELLANT
          name: pcqId
      case-type-ids:
        - Benefit

smoke.test.enabled: false

application-insights:
  default:
    modules:
      WebSyntheticRequestTelemetryInitializer:
        enabled: false

azure:
  application-insights:
    instrumentation-key: ${APPINSIGHTS_INSTRUMENTATIONKEY:"Test"}

pcqBackendUrl: ${PCQ_BACKEND_URL:http://localhost:4550}

feign:
  allow:
    headers:
      - x-correlation-id

coRelationId: PCQ Consolidation Service
